### ISSUE TITLE
Trouble Running 

### ISSUE THREAD

**Issue by dawei22** [swarris/PaSWAS#1]
When i try to run the examples, i get this

29181 mb of memory allocated on device number: 0
Read number of targets: 4
Read number of sequences: 392054
Starting alignments on target block 0
Number of alignments: 6331488 @ 0
CUDA error at ../gpuAlign.cu:166 code=77(cudaErrorIllegalAddress) "cudaMemcpy(d_sequences, h_sequences+(j*3174*(304)), sizeof(char) * (304)*3174, cudaMemcpyHostToDevice)" 

I'm using python3, CUDA 8, and a gtx1070 grafics card (8192 mb memory)

Someone knows about that error?

**Comment by swarris** [comment]
The amount of memory allocated by PaSWAS (29GB) exceeds the memory available on the GPU (8GB). 
You can run PaSWAS by editing PaSWAS/definition.h and change this line:
#define NUMBER_SEQUENCES 
to maybe something like this:
#define NUMBER_SEQUENCES 50000

You can also switch to the python enabled version:
https://github.com/swarris/pyPaSWAS
This tool will solve the configuration/compile issues you have automatically. Uses python 2.7 still, CUDA 8 is not a problem.
