### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by HerdiandKun** [swarris/PaSWAS#2]
I getting this error when i try to make gpuAlign.cu

gpuAlign.cu(86) : error: identifier "index" is undefined
gpuAlign.cu(120) : error: identifier "index" is undefined

Where is index variable?

**Comment by swarris** [comment]
The index function was part of string.h. It is now deprecated and part of legacy C: http://pubs.opengroup.org/onlinepubs/009695399/functions/index.html
You can fix it by replacing it with:  strchr() 
I'll do that for PaSWAS at a later stage also. However, the PaSWAS code base can also be considered legacy code. The newest version is in pyPaSWAS and I recommend you use that one:
https://github.com/swarris/pyPaSWAS

**Comment by HerdiandKun** [comment]
Okey thanks a lot. 
I've seen that too, but I want to try and learn this code for implement sw with cuda before using pycuda. 
What method is used in this code?
Columnwise, rowwise or antidiagonal?

**Comment by swarris** [comment]
The workings of the cuda implementation is fully explained in the paper:
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122524
